export default{
    fr: {
        "compte": "Mon Compte",
        "deco": "Déconnexion",
        
        "langue": "Langue",
        "pk": "Pourquoi RMOpportunities?",
        "offres": "Offres",
        "voir_offres": "Voir les offres",
        "aj_offre": "Ajouter une offre",
        "conseils": "Conseils",
        "acheter": "Acheter",
        "vendre": "Vendre",
        "reutil": "Réutiliser",
        "a_propos": "A Propos",
        "equipe": "L'équipe",
        "soutiens": "Nos soutiens",
        "presse": "Presse",
        "blog": "Blog",
        "decouvrir": "Découvrir",
        "manifeste": "Notre manifeste",
        "tarifs": "Nos tarifs",
        "faq": "FAQ",
        "contact": "Contact",
        "alertes": "Mes alertes produits",
        "annonces": "Mes annonces",
        "nego": "Mes négociations",
        "mises_en_rel": "Mes mises en relation",
        "factures": "Mes factures",
        "modif_compte": "Modifier mon compte",
        
        "connexion": "Connexion",
        "inscription": "Inscription",
        "recherche": "Recherche",
        "ttes_cat": "Toutes les catégories",
        "cosm": "Produits pour la cosmétique, les arômes et parfums",
        "solv": "Solvants",
        "solv_reg": "Solvants regeneres",
        "react": "Reactifs",
        "catal": "Catalyseurs",
        "spe_chi": "Specialites chimiques",
        "interm": "Intermediaires",
        "interm_simple": "Intermediaires simples",
        "acides": "Acides",
        "bases": "Bases",
        "acid_ami": "Acides amines",
        "vit": "Vitamines",
        "autres": "Autres",
        "trouver_par": "trouver par nom, n° CAS",

        "connect": "Connectez-vous",
        "se_co": "Se connecter",
        "nom_mail": "Nom ou e-mail de l'entreprise",
        "mdp": "Mot de passe",
        "mdp_oublie": "Mot de passe oublié?",
        "co_linkedin": "Se connecter avec Linkedin",
        "ou": "OU",

        "inscript": "Inscrivez-vous",
        "text_ins": "L'inscription de votre société sur RMOpportunities est simple, rapide et gratuite",
        "ins_linkedin": "S'inscrire avec Linkedin",
        "ins3etapes": "Démarrer l'inscription en 3 étapes",
        "info_entr": "Informations entreprise",
        "nom": "Nom entreprise",
        "adr": "Adresse entreprise",
        "compl_adr": "Complément d'adresse",
        "ville": "Ville",
        "code_post": "Code postal",
        "pays": "Pays",
        "tva": "N° TVA intracommunautaire",
        "info_contact": "Informations contact",
        "nom_contact": "Nom et prénom contact",
        "mail": "Adresse email contact",
        "tel": "N° de téléphone",
        "cgu": "Conditions d'utilisations",
        "texte_cgu1": "Je confirme avoir lu et accepté les ",
        "texte_cgu2": "Conditions d'utilisations de RMOpportunities",
        "texte_cgu3": ", que mes informations sont correctes et que je les maintiendrai à jour.",
        "sinscrire": "S'inscrire",

        "choix_img":"Choisissez une image" ,
        "annuler": "Annuler",
        "prendre_photo": "Prendre une photo",
        "choix_gallerie": "Choisir depuis la gallerie"
    },
    en: {
        "compte": "My Account",
        "deco": "Sign out",
        
        "langue": "Language",
        "pk": "Why RMOpportunities?",
        "offres": "Offers",
        "voir_offres": "See offers",
        "aj_offre": "Add an offer",
        "conseils": "Advice",
        "acheter": "Buy",
        "vendre": "Sell",
        "reutil": "Reuse",
        "a_propos": "About",
        "equipe": "The team",
        "soutiens": "Our supporters",
        "presse": "Press",
        "blog": "Blog",
        "decouvrir": "Discover",
        "manifeste": "Our manifesto",
        "tarifs": "Pricing",
        "faq": "FAQ",
        "contact": "Contact",
        "alertes": "My products alerts",
        "annonces": "My classifieds",
        "nego": "My negotiations",
        "mises_en_rel": "My connections",
        "factures": "My invoices",
        "modif_compte": "Edit account",
        
        "connexion": "Login",
        "inscription": "Sign Up",
        "recherche": "Search",
        "ttes_cat": "All categories",
        "cosm": "Products for cosmetics, flavorings and fragrances",
        "solv": "Solvents",
        "solv_reg": "Regenerated solvents",
        "react": "Reagents",
        "catal": "Catalysts",
        "spe_chi": "Chemical specialties",
        "interm": "Intermediates",
        "interm_simple": "Simple intermediates",
        "acides": "Acids",
        "bases": "Bases",
        "acid_ami": "Amino acids",
        "vit": "Vitamins",
        "autres": "Others",
        "trouver_par": "search by name, CAS number",

        "connect": "Log in",
        "se_co": "Log in",
        "nom_mail": "Company name or representative email address",
        "mdp": "Password",
        "mdp_oublie": "Forgot your password?",
        "co_linkedin": "Sign in with Linkedin",
        "ou": "OR",

        "inscript": "Sign up",
        "text_ins": "Create an account of your company on RMOpportunities is easy, quick and free",
        "ins_linkedin": "Sign up with Linkedin",
        "ins3etapes": "Sign up in 3 steps",
        "info_entr": "Company information",
        "nom": "Company name",
        "adr": "Street number and name",
        "compl_adr": "Address - additional information",
        "ville": "City",
        "code_post": "ZIP code",
        "pays": "Country",
        "tva": "VAT identification number",
        "info_contact": "Representative information",
        "nom_contact": "Contact name",
        "mail": "Email address",
        "tel": "Phone number",
        "cgu": "General terms and conditions",
        "texte_cgu1": "I acknowledge that I have read the ",
        "texte_cgu2": " General terms and conditions of RMOpportunities",
        "texte_cgu3": ", that the informations entered are correct and that I will update them if necessary.",
        "sinscrire": "Get started",

        "choix_img":"Choose an image" ,
      "annuler": "Cancel",
      "prendre_photo": "Take a picture",
      "choix_gallerie": "Choose from gallery"
    }
}
